authorization: woshimima

lb_policy: order # 负载均衡策略，可选值为 order 和 random

# 使用 sqlite 作为数据库储存请求记录
dbtype: sqlite
dbaddr: ./db.sqlite

# 使用 postgres 作为数据库储存请求记录
# dbtype: postgres
# dbaddr: "host=127.0.0.1 port=5432 user=postgres dbname=openai_api_route sslmode=disable password=woshimima"

# 不使用数据库记录
# dbtype: none

upstreams:
  - sk: "secret_key_1"
    endpoint: "https://api.openai.com/v2"
    allow: ["gpt-3.5-trubo"] # 可选的模型白名单
  - sk: "secret_key_2"
    endpoint: "https://api.openai.com/v1"
    timeout: 30
    allow: ["gpt-3.5-trubo"] # 可选的模型白名单
    deny: ["gpt-4"] # 可选的模型黑名单
    # 若白名单和黑名单同时设置，先判断白名单，再判断黑名单
  - sk: "key_for_replicate"
    type: replicate
    allow: ["mistralai/mixtral-8x7b-instruct-v0.1"]
